Repository doceo/plant, pull requests merged in 2018-04, with the labels that each got.

#39 interfaccia grafica
  html/index.html
Labels: funzionalità base, grafica

#35 Graph
  html/index.html
Labels: funzionalità base, grafica

#42 Aggiornamento della struttura dei tre grafici
  html/index.html
Labels: funzionalità base, grafica

#32 aggiunta mongodb
  app.js
  package-lock.json
  package.json
Labels: Core, funzionalità base

#47 node + gateway
  doc/RadioHead-1.83.zip
  doc/Server fritzing.PNG
  doc/start up server e client.docx
  nRF24_client/dht.cpp
  nRF24_client/dht.h
  nRF24_client/nRF24_client.ino
  nRF24_server/DateStrings.cpp
  nRF24_server/EspDrv.cpp
  nRF24_server/EspDrv.h
  nRF24_server/PubSubClient.cpp
  nRF24_server/PubSubClient.h
  nRF24_server/RingBuffer.cpp
  nRF24_server/RingBuffer.h
  nRF24_server/Time.cpp
  nRF24_server/Time.h
  nRF24_server/TimeLib.h
  nRF24_server/WiFiEsp.cpp
  nRF24_server/WiFiEsp.h
  nRF24_server/WiFiEspClient.cpp
  nRF24_server/WiFiEspClient.h
  nRF24_server/WiFiEspServer.cpp
  nRF24_server/WiFiEspServer.h
  nRF24_server/WiFiEspUdp.cpp
  nRF24_server/WiFiEspUdp.h
  nRF24_server/debug.h
  nRF24_server/nRF24_server.ino
  nRF24_server/utility/EspDrv.cpp
  nRF24_server/utility/EspDrv.h
  nRF24_server/utility/RingBuffer.cpp
  nRF24_server/utility/RingBuffer.h
  nRF24_server/utility/debug.h
Labels: Core

#45 modifica changelog
  doc/CHANGELOG.md
Labels: Documentazione
